import React, { ElementType, ReactNode, useEffect, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { motion, useScroll, useTransform, MotionValue } from 'framer-motion';
import { ArrowUpRight } from 'lucide-react';
import './index.css';

const gifs = [
  'https://motionsites.ai/assets/hero-space-voyage-preview-eECLH3Yc.gif','https://motionsites.ai/assets/hero-codenest-preview-Cgppc2qV.gif','https://motionsites.ai/assets/hero-vex-ventures-preview-BczMFIiw.gif','https://motionsites.ai/assets/hero-stellar-ai-v2-preview-DjvxjG3C.gif','https://motionsites.ai/assets/hero-asme-preview-B_nGDnTP.gif','https://motionsites.ai/assets/hero-transform-data-preview-Cx5OU29N.gif','https://motionsites.ai/assets/hero-vitara-preview-Cjz2QYyU.gif','https://motionsites.ai/assets/hero-terra-preview-BFjrCr7T.gif','https://motionsites.ai/assets/hero-skyelite-preview-DHaZIgUv.gif','https://motionsites.ai/assets/hero-aethera-preview-DknSlcTa.gif','https://motionsites.ai/assets/hero-designpro-preview-D8c5_een.gif','https://motionsites.ai/assets/hero-stellar-ai-preview-D3HL6bw1.gif','https://motionsites.ai/assets/hero-xportfolio-preview-D4A8maiC.gif','https://motionsites.ai/assets/hero-orbit-web3-preview-BXt4OttD.gif','https://motionsites.ai/assets/hero-nexora-preview-cx5HmUgo.gif','https://motionsites.ai/assets/hero-evr-ventures-preview-DZxeVFEX.gif','https://motionsites.ai/assets/hero-planet-orbit-preview-DWAP8Z1P.gif','https://motionsites.ai/assets/hero-new-era-preview-CocuDUm9.gif','https://motionsites.ai/assets/hero-wealth-preview-B70idl_u.gif','https://motionsites.ai/assets/hero-luminex-preview-CxOP7ce6.gif','https://motionsites.ai/assets/hero-celestia-preview-0yO3jXO8.gif'
];

const projects = [
  { n:'01', category:'Asset Production Lead', name:'WIZARD', label:'Open WIZARD', desc:'2470 indexed assets become searchable production intent.', imgs:['https://images.higgs.ai/?default=1&output=webp&url=https%3A%2F%2Fd8j0ntlcm91z4.cloudfront.net%2Fuser_38xzZboKViGWJOttwIXH07lWA1P%2Fhf_20260412_055344_5eff02e0-87a5-41ce-b64f-eb08da8f33db.png&w=1280&q=85','https://images.higgs.ai/?default=1&output=webp&url=https%3A%2F%2Fd8j0ntlcm91z4.cloudfront.net%2Fuser_38xzZboKViGWJOttwIXH07lWA1P%2Fhf_20260412_055431_11d841fd-8b41-46a5-82e4-b04f2407a7d8.png&w=1280&q=85','https://images.higgs.ai/?default=1&output=webp&url=https%3A%2F%2Fd8j0ntlcm91z4.cloudfront.net%2Fuser_38xzZboKViGWJOttwIXH07lWA1P%2Fhf_20260412_055451_e317bf2d-28d4-48cc-86b0-6f72f25b6327.png&w=1280&q=85']},
  { n:'02', category:'Sprite Pipeline', name:'SWIFT', label:'Open SWIFT', desc:'3D input becomes 2D game-ready output.', imgs:['https://images.higgs.ai/?default=1&output=webp&url=https%3A%2F%2Fd8j0ntlcm91z4.cloudfront.net%2Fuser_38xzZboKViGWJOttwIXH07lWA1P%2Fhf_20260412_055654_911201c5-36d9-4bc6-bac7-331adfce159f.png&w=1280&q=85','https://images.higgs.ai/?default=1&output=webp&url=https%3A%2F%2Fd8j0ntlcm91z4.cloudfront.net%2Fuser_38xzZboKViGWJOttwIXH07lWA1P%2Fhf_20260412_055723_5ceda0b8-d9c2-4665-b2e3-83ba19ba76d1.png&w=1280&q=85','https://images.higgs.ai/?default=1&output=webp&url=https%3A%2F%2Fd8j0ntlcm91z4.cloudfront.net%2Fuser_38xzZboKViGWJOttwIXH07lWA1P%2Fhf_20260412_055753_adc5dcbd-a8e6-49c0-b43a-9b030d835cea.png&w=1280&q=85']},
  { n:'03', category:'Visible World Rules', name:'SHADED', label:'Open SHADED', desc:'Shader systems turn world state into readable truth.', imgs:['https://images.higgs.ai/?default=1&output=webp&url=https%3A%2F%2Fd8j0ntlcm91z4.cloudfront.net%2Fuser_38xzZboKViGWJOttwIXH07lWA1P%2Fhf_20260412_055759_963cfb0b-4bd1-4b0f-9d0a-09bd6cf95b2f.png&w=1280&q=85','https://images.higgs.ai/?default=1&output=webp&url=https%3A%2F%2Fd8j0ntlcm91z4.cloudfront.net%2Fuser_38xzZboKViGWJOttwIXH07lWA1P%2Fhf_20260412_060108_438f781a-9846-4dcc-89ab-c4e6cb830f5b.png&w=1280&q=85','https://images.higgs.ai/?default=1&output=webp&url=https%3A%2F%2Fd8j0ntlcm91z4.cloudfront.net%2Fuser_38xzZboKViGWJOttwIXH07lWA1P%2Fhf_20260412_055818_9d062121-ad7e-46b9-999a-1a6a692ef1ee.png&w=1280&q=85']}
];

function FadeIn({children, delay=0, duration=0.7, x=0, y=30, as='div', className=''}:{children:ReactNode;delay?:number;duration?:number;x?:number;y?:number;as?:ElementType;className?:string}) {
  const Component = motion.create(as);
  return <Component className={className} initial={{opacity:0,x,y}} whileInView={{opacity:1,x:0,y:0}} viewport={{once:true, margin:'50px', amount:0}} transition={{delay,duration,ease:[0.25,0.1,0.25,1]}}>{children}</Component>;
}

function ContactButton({label='Enter Workshop'}:{label?:string}) { return <button className="rounded-full px-8 py-3 text-xs font-medium uppercase tracking-widest text-white outline outline-2 -outline-offset-[3px] outline-white transition hover:scale-105 sm:px-10 sm:py-3.5 sm:text-sm md:px-12 md:py-4 md:text-base" style={{background:'linear-gradient(123deg, #18011F 7%, #B600A8 37%, #7621B0 72%, #BE4C00 100%)', boxShadow:'0px 4px 4px rgba(181, 1, 167, 0.25), 4px 4px 12px #7721B1 inset'}}>{label}</button>; }
function LiveProjectButton({label='Open Project'}:{label?:string}) { return <button className="inline-flex items-center gap-2 rounded-full border-2 border-[#D7E2EA] px-8 py-3 text-sm font-medium uppercase tracking-widest text-[#D7E2EA] transition hover:bg-[#D7E2EA]/10 sm:px-10 sm:py-3.5 sm:text-base">{label}<ArrowUpRight size={18}/></button>; }

function Magnet({children}:{children:ReactNode}) { const ref=useRef<HTMLDivElement>(null); const [t,setT]=useState('translate3d(0,0,0)'); const [tr,setTr]=useState('transform 0.6s ease-in-out'); useEffect(()=>{const move=(e:MouseEvent)=>{const el=ref.current;if(!el)return;const r=el.getBoundingClientRect();const pad=150;const inside=e.clientX>=r.left-pad&&e.clientX<=r.right+pad&&e.clientY>=r.top-pad&&e.clientY<=r.bottom+pad;if(inside){setTr('transform 0.3s ease-out');setT(`translate3d(${(e.clientX-(r.left+r.width/2))/3}px, ${(e.clientY-(r.top+r.height/2))/3}px, 0)`)}else{setTr('transform 0.6s ease-in-out');setT('translate3d(0,0,0)')}};window.addEventListener('mousemove',move);return()=>window.removeEventListener('mousemove',move)},[]); return <div ref={ref} style={{transform:t,transition:tr,willChange:'transform'}}>{children}</div>; }

function HeroSection(){return <section className="relative flex h-screen flex-col overflow-x-clip bg-[#0C0C0C] px-6 md:px-10"><FadeIn y={-20} className="z-20 flex justify-between pt-6 text-sm font-medium uppercase tracking-wider text-[#D7E2EA] md:pt-8 md:text-lg lg:text-[1.4rem]"><a>About</a><a>Systems</a><a>Projects</a><a>Contact</a></FadeIn><div className="overflow-hidden"><FadeIn as="h1" delay={0.15} y={40} className="hero-heading mt-6 w-full whitespace-nowrap text-[14vw] font-black uppercase leading-none tracking-tight sm:mt-4 sm:text-[15vw] md:-mt-5 md:text-[16vw] lg:text-[17.5vw]">Hi, i'm Lootz</FadeIn></div><FadeIn delay={0.6} y={30} className="absolute left-1/2 top-1/2 z-10 w-[280px] -translate-x-1/2 -translate-y-1/2 sm:bottom-0 sm:top-auto sm:w-[360px] sm:translate-y-0 md:w-[440px] lg:w-[520px]"><Magnet><img className="w-full" src="https://shrug-person-78902957.figma.site/_components/v2/d24c01ad3a56fc65e942a1f501eb73db42d7cf9a/Rectangle_40443.81459862.png" /></Magnet></FadeIn><div className="z-20 mt-auto flex items-end justify-between pb-7 sm:pb-8 md:pb-10"><FadeIn delay={0.35} y={20} className="max-w-[180px] text-[clamp(0.75rem,1.4vw,1.5rem)] font-light uppercase leading-snug tracking-wide text-[#D7E2EA] sm:max-w-[240px] md:max-w-[300px]">a non-technical worldbuilder turning sentences, assets, shaders, and agents into playable systems</FadeIn><FadeIn delay={0.5} y={20}><ContactButton /></FadeIn></div></section>}

function MarqueeSection(){const ref=useRef<HTMLElement>(null);const [offset,setOffset]=useState(0);useEffect(()=>{const on=()=>{if(ref.current)setOffset((window.scrollY-ref.current.offsetTop+window.innerHeight)*0.3)};on();window.addEventListener('scroll',on,{passive:true});return()=>window.removeEventListener('scroll',on)},[]);const row=(arr:string[], dir:number)=><div className="flex gap-3" style={{transform:`translateX(${dir===1?offset-200:-(offset-200)}px)`,willChange:'transform'}}>{[...arr,...arr,...arr].map((src,i)=><img key={src+i} loading="lazy" src={src} className="h-[270px] w-[420px] shrink-0 rounded-2xl object-cover"/>)}</div>;return <section ref={ref} className="overflow-hidden bg-[#0C0C0C] pb-10 pt-24 sm:pt-32 md:pt-40"><div className="flex flex-col gap-3">{row(gifs.slice(0,11),1)}{row(gifs.slice(11),-1)}</div></section>}

function AnimatedText({text}:{text:string}){const ref=useRef<HTMLParagraphElement>(null);const {scrollYProgress}=useScroll({target:ref,offset:['start 0.8','end 0.2']});return <p ref={ref} className="max-w-[680px] text-center text-[clamp(1rem,2vw,1.35rem)] font-medium leading-relaxed text-[#D7E2EA]">{text.split('').map((ch,i)=>{const start=i/text.length;const opacity=useTransform(scrollYProgress,[start,Math.min(start+0.12,1)],[0.2,1]);return <span key={i} className="relative inline-block"><span className="invisible">{ch}</span><motion.span style={{opacity}} className="absolute inset-0">{ch}</motion.span></span>})}</p>}
function AboutSection(){const text="I don't build apps because I love code. I build systems because thoughts need shapes. WIZARD turns ideas into asset kits. SWIFT turns models into usable game sprites. SHADED turns visible changes into world rules. The code is only the machinery. The point is less friction between imagination and something you can actually play.";return <section className="relative flex min-h-screen items-center justify-center overflow-hidden bg-[#0C0C0C] px-5 py-20 sm:px-8 md:px-10"><FadeIn delay={0.1} x={-80} y={0} duration={0.9} className="absolute left-[1%] top-[4%] w-[120px] sm:left-[2%] sm:w-[160px] md:left-[4%] md:w-[210px]"><img src="https://shrug-person-78902957.figma.site/_components/v2/ebb2b8f25d8e24d5f0a5ca8af4c950de81aa2fd7/moon_icon.11395d36.png"/></FadeIn><FadeIn delay={0.25} x={-80} y={0} duration={0.9} className="absolute bottom-[8%] left-[3%] w-[100px] sm:left-[6%] sm:w-[140px] md:left-[10%] md:w-[180px]"><img src="https://shrug-person-78902957.figma.site/_components/v2/ebb2b8f25d8e24d5f0a5ca8af4c950de81aa2fd7/p59_1.4659672e.png"/></FadeIn><FadeIn delay={0.15} x={80} y={0} duration={0.9} className="absolute right-[1%] top-[4%] w-[120px] sm:right-[2%] sm:w-[160px] md:right-[4%] md:w-[210px]"><img src="https://shrug-person-78902957.figma.site/_components/v2/ebb2b8f25d8e24d5f0a5ca8af4c950de81aa2fd7/lego_icon-1.703bb594.png"/></FadeIn><FadeIn delay={0.3} x={80} y={0} duration={0.9} className="absolute bottom-[8%] right-[3%] w-[130px] sm:right-[6%] sm:w-[170px] md:right-[10%] md:w-[220px]"><img src="https://shrug-person-78902957.figma.site/_components/v2/ebb2b8f25d8e24d5f0a5ca8af4c950de81aa2fd7/Group_134-1.2e04f3ce.png"/></FadeIn><div className="z-10 flex flex-col items-center gap-10 sm:gap-14 md:gap-16"><FadeIn as="h2" y={40} className="hero-heading text-center text-[clamp(3rem,12vw,160px)] font-black uppercase leading-none tracking-tight">About me</FadeIn><div className="flex flex-col items-center gap-16 sm:gap-20 md:gap-24"><AnimatedText text={text}/><ContactButton label="Ask what I'm building"/></div></div></section>}

const systems=[['01','WIZARD','Semantic production lead for game assets. Describe a game idea and WIZARD translates it into environments, characters, props, templates, gaps, and a usable starter kit.'],['02','SWIFT','Procedural sprite and render pipeline. Turns 3D models, sketches, or visual ideas into clean previews, sprite sheets, turntables, masks, and game-ready output.'],['03','SHADED','Shader-first world logic. Rain, snow, mud, fire, grass, fog, decay, and material states become visible rules instead of decorative effects.'],['04','CUE / Evidence','Agent verification layer. Claims require evidence, screenshots, logs, and repeatable checks before a system is allowed to call something done.'],['05','mini-me / Language','A prompt-shaped writing engine distilled from my own texts. It turns strange inputs into internally consistent stories, pitches, and narrative systems.']];
function SystemsSection(){return <section className="rounded-t-[40px] bg-white px-5 py-20 sm:rounded-t-[50px] sm:px-8 sm:py-24 md:rounded-t-[60px] md:px-10 md:py-32"><h2 className="mb-16 text-center text-[clamp(3rem,12vw,160px)] font-black uppercase leading-none text-[#0C0C0C] sm:mb-20 md:mb-28">Systems</h2><div className="mx-auto max-w-5xl">{systems.map(([n,name,desc],i)=><FadeIn key={n} delay={i*0.1} className="flex gap-6 border-t border-[rgba(12,12,12,0.15)] py-8 last:border-b sm:gap-10 sm:py-10 md:py-12"><div className="w-[28%] text-[clamp(3rem,10vw,140px)] font-black leading-none text-[#0C0C0C]">{n}</div><div className="flex flex-1 flex-col justify-center"><h3 className="text-[clamp(1rem,2.2vw,2.1rem)] font-medium uppercase">{name}</h3><p className="max-w-2xl text-[clamp(0.85rem,1.6vw,1.25rem)] font-light leading-relaxed opacity-60">{desc}</p></div></FadeIn>)}</div></section>}
function ProjectCard({p,index}:{p:typeof projects[number];index:number}){const ref=useRef<HTMLDivElement>(null);const {scrollYProgress}=useScroll({target:ref,offset:['start end','end start']});const targetScale=1-(projects.length-1-index)*0.03;const scale=useTransform(scrollYProgress,[0,1],[1,targetScale]);return <div ref={ref} className="h-[85vh]"><motion.div style={{scale,top:`${index*28}px`}} className="sticky top-24 rounded-[40px] border-2 border-[#D7E2EA] bg-[#0C0C0C] p-4 sm:rounded-[50px] sm:p-6 md:top-32 md:rounded-[60px] md:p-8"><div className="mb-6 flex flex-wrap items-end justify-between gap-4 text-[#D7E2EA]"><div className="flex items-end gap-5"><span className="text-[clamp(3rem,10vw,140px)] font-black leading-none">{p.n}</span><div><p className="text-sm uppercase tracking-widest opacity-70">{p.category}</p><h3 className="text-[clamp(2rem,6vw,5rem)] font-black uppercase leading-none">{p.name}</h3><p className="mt-2 font-light opacity-70">{p.desc}</p></div></div><LiveProjectButton label={p.label}/></div><div className="flex gap-4"><div className="flex w-[40%] flex-col gap-4"><img className="h-[clamp(130px,16vw,230px)] rounded-[40px] object-cover sm:rounded-[50px] md:rounded-[60px]" src={p.imgs[0]}/><img className="h-[clamp(160px,22vw,340px)] rounded-[40px] object-cover sm:rounded-[50px] md:rounded-[60px]" src={p.imgs[1]}/></div><img className="w-[60%] rounded-[40px] object-cover sm:rounded-[50px] md:rounded-[60px]" src={p.imgs[2]}/></div></motion.div></div>}
function ProjectsSection(){return <section className="relative z-10 -mt-10 rounded-t-[40px] bg-[#0C0C0C] px-5 py-20 sm:-mt-12 sm:rounded-t-[50px] sm:px-8 md:-mt-14 md:rounded-t-[60px] md:px-10"><h2 className="hero-heading mb-16 text-center text-[clamp(3rem,12vw,160px)] font-black uppercase leading-none tracking-tight">Projects</h2><div className="mx-auto max-w-7xl">{projects.map((p,i)=><ProjectCard key={p.name} p={p} index={i}/>)}</div></section>}
function App(){return <main className="bg-[#0C0C0C]" style={{overflowX:'clip'}}><HeroSection/><MarqueeSection/><AboutSection/><SystemsSection/><ProjectsSection/></main>}

createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
